# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Portfolio
email: madison.m.carpenter1@gmail.com
description: >-
  Bioinformatician exploring Alzheimer's, ALS, and MS 🧠🔬, using multi-omics and modeling to uncover disease mechanisms.
github_username: madison-car
homepage_layout: splash
minimal_mistakes_skin: mint
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 1 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York

include:
  - _pages

# Site Masthead logo
logo: "/assets/images/Puppy.png"
masthead_title: "My Custom Title"

# Header
excerpt: "This post should display a **header with a solid background color**, if the theme supports it."
header:
  overlay_color: "#333"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author information
author:
  name: "Madison Carpenter"
  avatar: "/assets/images/Me.png"
  bio: "Bioinformatician exploring Alzheimer's, ALS, and MS 🧠🔬, using multi-omics and modeling to uncover disease mechanisms."
  links:
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://youtube.com/@madisoncarpenter"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/madison-car"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/madisoncarpenter"

footer:
  links:
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://youtube.com/@madisoncarpenter"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/madison-car"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/madisoncarpenter"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: "post"
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: "splash"
      permalink: /
      author_profile: true

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

